name: Build MineyMods-Core

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'   # Java 17 is recommended for Minecraft 1.20+
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: MineyMods-Core-JAR
          path: target/*.jar
